version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:15.1
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: blogs_test
          POSTGRES_PASSWORD: 1234
     
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v4-{{ .Branch }}-{{checksum "client/package-lock.json"}}
            - node-deps-v4-
      - run:
          name: install packages client
          command: |
            ls
            cd client
            npm install
      - save_cache:
          key: node-deps-v4-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - client/node_modules
      - restore_cache:
          keys:
            - server-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
            - server-v1-
      - run:
          name: install packages server
          command: |
            ls
            npm install 
      - save_cache:
          key: server-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - node_modules
      - run:
          name: Run server
          command: npm run server-test
          background: true
          
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run database migration
          command: npm run migrate up
      - run:
          name: Seed database
          command: npm run data-import-test 
      - run:
          name: Kill server
          command: sudo kill node
      - run:
          name: Test server
          command: npm run test-server           

workflows:
  orb-free-workflow:
    jobs:
      - test
