version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Invoke the Heroku orb

jobs:
  test:
    docker:
      - image: cypress/base:14.15.0
        environment:
          ## this enables colors in the output
          TERM: xterm
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: blogs_test
          POSTGRES_PASSWORD: 1234

    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v7-{{ .Branch }}-{{checksum "client/package-lock.json"}}
            - node-deps-v7-
      - run:
          name: install packages client
          command: |
            ls
            cd client
            npm install
      - save_cache:
          key: node-deps-v7-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - client/node_modules
      - restore_cache:
          keys:
            - server-v6-{{ .Branch }}-{{checksum "package-lock.json"}}
            - server-v6-
      - run:
          name: install packages server
          command: |
            ls
            npm install
      - save_cache:
          key: server-v6-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - node_modules
            - /root/.cache/Cypress
      - run:
          name: Run server
          command: npm run server-test
          background: true

      - run:
          name: Wait for db
          command: while netstat -lnt | awk '$4 ~ /:5000$/ {exit 1}'; do sleep 0.1; done

      - run:
          name: Run database migration
          command: npm run migrate up
      - run:
          name: Seed database
          command: npm run data-import-test
      - run:
          name: Kill server
          command: pkill -f node
      - run:
          name: Run test dev servers
          command: npm run dev-test
          background: true
      - run:
          name: Run test
          command: npm run test
      - run:
          name: Run cypress test
          command: ./node_modules/.bin/cypress run --record --key da752f1c-8d75-465b-bf14-fcbf13c7fc1c

workflows:
  heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - test
          filters:
            branches:
              only: main
